import type { AlgorithmComparisonMeta } from '../types/algorithmSelection';

export const DEFAULT_ALGORITHM_META: AlgorithmComparisonMeta = {
  summary: '알고리즘 메타 정보가 아직 등록되지 않았습니다.',
  accuracy: '보통',
  trainSpeed: '보통',
  predictSpeed: '보통',
  complexity: '중간',
  interpretability: '보통',
};

export const ALGORITHM_META_BY_CODE: Record<string, AlgorithmComparisonMeta> = {
  RANDOM_FOREST: {
    accuracy: '높음',
    trainSpeed: '느림',
    predictSpeed: '보통',
    complexity: '중간',
    interpretability: '낮음',
    summary: '여러 트리를 결합해 안정적인 분류 수행',
  },
  XGBOOST: {
    accuracy: '매우 높음',
    trainSpeed: '느림',
    predictSpeed: '보통',
    complexity: '높음',
    interpretability: '낮음',
    summary: '오차를 반복 보완하는 부스팅 모델',
  },
  LIGHTGBM: {
    accuracy: '매우 높음',
    trainSpeed: '빠름',
    predictSpeed: '빠름',
    complexity: '높음',
    interpretability: '낮음',
    summary: '빠르고 효율적인 부스팅 모델',
  },
  LOGISTIC_REGRESSION: {
    accuracy: '보통',
    trainSpeed: '빠름',
    predictSpeed: '매우 빠름',
    complexity: '낮음',
    interpretability: '매우 높음',
    summary: '확률 기반 선형 분류 모델',
  },
  SVM: {
    accuracy: '높음',
    trainSpeed: '느림',
    predictSpeed: '보통',
    complexity: '높음',
    interpretability: '낮음',
    summary: '경계를 최대화하는 분류 모델',
  },
  MLP: {
    accuracy: '높음',
    trainSpeed: '느림',
    predictSpeed: '보통',
    complexity: '높음',
    interpretability: '낮음',
    summary: '신경망 기반 분류 모델',
  },
  LINEAR_REGRESSION: {
    accuracy: '보통',
    trainSpeed: '매우 빠름',
    predictSpeed: '매우 빠름',
    complexity: '낮음',
    interpretability: '매우 높음',
    summary: '선형 관계 기반 값 예측',
  },
  RANDOM_FOREST_REGRESSOR: {
    accuracy: '높음',
    trainSpeed: '느림',
    predictSpeed: '보통',
    complexity: '중간',
    interpretability: '낮음',
    summary: '트리 기반 회귀 모델',
  },
  XGBOOST_REGRESSOR: {
    accuracy: '매우 높음',
    trainSpeed: '느림',
    predictSpeed: '보통',
    complexity: '높음',
    interpretability: '낮음',
    summary: '부스팅 기반 고성능 회귀',
  },
  LIGHTGBM_REGRESSOR: {
    accuracy: '매우 높음',
    trainSpeed: '빠름',
    predictSpeed: '빠름',
    complexity: '높음',
    interpretability: '낮음',
    summary: '빠른 부스팅 회귀',
  },
  ANN: {
    accuracy: '높음',
    trainSpeed: '느림',
    predictSpeed: '보통',
    complexity: '높음',
    interpretability: '낮음',
    summary: '신경망 기반 회귀',
  },
  ISOLATION_FOREST: {
    accuracy: '높음',
    trainSpeed: '빠름',
    predictSpeed: '빠름',
    complexity: '중간',
    interpretability: '낮음',
    summary: '랜덤 분할로 이상치 탐지',
  },
  ONE_CLASS_SVM: {
    accuracy: '보통',
    trainSpeed: '느림',
    predictSpeed: '느림',
    complexity: '높음',
    interpretability: '낮음',
    summary: '정상 데이터 기준 이상 탐지',
  },
  AUTO_ENCODER: {
    accuracy: '높음',
    trainSpeed: '느림',
    predictSpeed: '보통',
    complexity: '높음',
    interpretability: '낮음',
    summary: '재구성 오차 기반 탐지',
  },
  AUTOENCODER: {
    accuracy: '높음',
    trainSpeed: '느림',
    predictSpeed: '보통',
    complexity: '높음',
    interpretability: '낮음',
    summary: '재구성 오차 기반 탐지',
  },
  LSTM_AE: {
    accuracy: '매우 높음',
    trainSpeed: '매우 느림',
    predictSpeed: '느림',
    complexity: '매우 높음',
    interpretability: '낮음',
    summary: '시계열 기반 이상 탐지',
  },
  LSTM: {
    accuracy: '매우 높음',
    trainSpeed: '매우 느림',
    predictSpeed: '느림',
    complexity: '매우 높음',
    interpretability: '낮음',
    summary: '시계열 패턴 학습',
  },
  GRU: {
    accuracy: '높음',
    trainSpeed: '느림',
    predictSpeed: '보통',
    complexity: '높음',
    interpretability: '낮음',
    summary: 'LSTM보다 가벼운 구조',
  },
  TCN: {
    accuracy: '높음',
    trainSpeed: '보통',
    predictSpeed: '빠름',
    complexity: '높음',
    interpretability: '낮음',
    summary: 'CNN 기반 시계열 모델',
  },
  ARIMA: {
    accuracy: '보통',
    trainSpeed: '보통',
    predictSpeed: '빠름',
    complexity: '중간',
    interpretability: '높음',
    summary: '통계 기반 시계열 예측',
  },
  PROPHET: {
    accuracy: '보통',
    trainSpeed: '빠름',
    predictSpeed: '빠름',
    complexity: '낮음',
    interpretability: '높음',
    summary: '트렌드/계절성 기반 모델',
  },
  KMEANS: {
    accuracy: '보통',
    trainSpeed: '매우 빠름',
    predictSpeed: '매우 빠름',
    complexity: '낮음',
    interpretability: '보통',
    summary: '거리 기반 군집화',
  },
  DBSCAN: {
    accuracy: '높음',
    trainSpeed: '느림',
    predictSpeed: '보통',
    complexity: '중간',
    interpretability: '보통',
    summary: '밀도 기반 군집화',
  },
  HIERARCHICAL_CLUSTERING: {
    accuracy: '높음',
    trainSpeed: '매우 느림',
    predictSpeed: '느림',
    complexity: '높음',
    interpretability: '높음',
    summary: '계층 구조 군집화',
  },
  HIERARCHICAL: {
    accuracy: '높음',
    trainSpeed: '매우 느림',
    predictSpeed: '느림',
    complexity: '높음',
    interpretability: '높음',
    summary: '계층 구조 군집화',
  },
};

export function getAlgorithmMeta(algoCd: string): AlgorithmComparisonMeta {
  return ALGORITHM_META_BY_CODE[algoCd] ?? DEFAULT_ALGORITHM_META;
}
